CREATE TABLE IF NOT EXISTS mealplan (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
    goal VARCHAR(50) NOT NULL,
    calories INT,
    plan_date TIMESTAMP,

);

CREATE INDEX